# Generated by Django 4.1.5 on 2023-06-06 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        #
        ),
    ]
